version: '3'
services:
  vchat-ui:
    build: 
      context: ./
    ports:
      - "3000:3000"
    container_name: vchat-ui
    env_file:
    - ./.env
    stdin_open: true
    volumes:
       - ./:/usr/src/app/
       - /usr/src/app/node_modules